import { LinearGradient } from 'expo-linear-gradient';
import { useRef, useState } from 'react';
import { Animated, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { acrossSportabase, sports, storylines, type SportKey } from './discovery-data';
import { DesignLabHeader } from './DesignLabHeader';
import { palette } from './design-lab-theme';
import type { ResultKey } from './mock-results';

const stateColors:Record<string,string>={Developing:'#818CF8',Substantial:'#D946EF',Contested:'#D946EF',Confirmed:'#82E85B',Opinion:'#A78BFA',Limited:'#FACC15',Unsupported:'#FB7185'};
export function DesignLabHome({ mobile, onAnalyze, onOpenResult, error, initialUrl, exitProgress, showHeader = true }: { mobile: boolean; onAnalyze: (url: string) => void; onOpenResult:(key:ResultKey)=>void; error?: string; initialUrl?: string; exitProgress: Animated.Value; showHeader?: boolean }) {
  const [url,setUrl]=useState(initialUrl??''),[sport,setSport]=useState<SportKey>('Football'); const press=useRef(new Animated.Value(1)).current;
  const submit=()=>{Animated.sequence([Animated.timing(press,{toValue:.98,duration:100,useNativeDriver:Platform.OS!=='web'}),Animated.timing(press,{toValue:1,duration:90,useNativeDriver:Platform.OS!=='web'})]).start(()=>onAnalyze(url))};
  const copyExit={opacity:exitProgress.interpolate({inputRange:[0,.56,1],outputRange:[1,0,0]}),transform:[{translateY:exitProgress.interpolate({inputRange:[0,.56,1],outputRange:[0,-10,-10]})}]};
  const inputExit={opacity:exitProgress.interpolate({inputRange:[0,.36,1],outputRange:[1,1,0]}),transform:[{scale:exitProgress.interpolate({inputRange:[0,.36,1],outputRange:[1,1,.985]})}]};
  return <View style={styles.page}>{showHeader?<DesignLabHeader mobile={mobile} onHome={()=>{}} onAnother={()=>{}} showAnother={false}/>:null}
    <View style={[styles.hero,mobile&&styles.heroMobile]}><Animated.View style={copyExit}><Text style={[styles.headline,mobile&&styles.headlineMobile]}>Know what backs the story.</Text><Text style={[styles.copy,mobile&&styles.copyMobile]}>Paste a sports story. See the central claim, the informational Merit of the reporting, and the evidence behind it.</Text></Animated.View>
      <Animated.View style={[styles.actionRow,mobile&&styles.actionRowMobile,inputExit,{transform:[...inputExit.transform,{scale:Animated.multiply(inputExit.transform[0].scale,press)}]}]}><TextInput accessibilityLabel="Sports story URL" value={url} onChangeText={setUrl} onSubmitEditing={submit} placeholder="Paste a sports story URL" placeholderTextColor={palette.muted} keyboardType="url" autoCapitalize="none" style={styles.input}/><Pressable accessibilityRole="button" onPress={submit} style={({pressed})=>[styles.buttonShell,mobile&&styles.buttonMobile,pressed&&styles.pressed]}><LinearGradient colors={[palette.cyan,palette.teal,palette.lime]} start={{x:0,y:.5}} end={{x:1,y:.5}} style={styles.button}><Text style={styles.buttonText}>Analyze</Text><Text style={styles.arrow}>→</Text></LinearGradient></Pressable></Animated.View>{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}
    </View>
    <Animated.View style={copyExit}><View style={styles.sectionHeader}><View><Text style={styles.eyebrow}>Discover</Text><Text style={styles.sectionTitle}>Top storylines</Text></View>{!mobile?<Text style={styles.sectionNote}>Signals across the current sports cycle</Text>:null}</View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.sportSelector}>{sports.map(item=><Pressable key={item} accessibilityRole="button" accessibilityState={{selected:sport===item}} onPress={()=>setSport(item)} style={[styles.sportOption,sport===item&&styles.sportOptionActive]}><Text style={[styles.sportText,sport===item&&styles.sportTextActive]}>{item}</Text></Pressable>)}</ScrollView>
      <View style={[styles.storyGrid,mobile&&styles.storyGridMobile]}>{storylines[sport].map((item,index)=><Pressable key={item.title} accessibilityRole="button" onPress={()=>onOpenResult(item.resultKey)} style={({pressed})=>[styles.storyline,mobile&&styles.storylineMobile,pressed&&styles.pressed]}><View style={styles.storyTop}><Text style={styles.storyContext}>{item.context}</Text><Text style={styles.storyIndex}>0{index+1}</Text></View><Text style={styles.storyTitle}>{item.title}</Text><Text style={styles.storyDescription}>{item.description}</Text><View style={styles.storySignal}><View style={[styles.signalMark,{backgroundColor:stateColors[item.state]??palette.teal}]}/><Text style={[styles.storyState,{color:stateColors[item.state]??palette.teal}]}>{item.state}</Text><Text style={styles.storyCount}>{item.reports} reports · {item.independent} independent</Text></View></Pressable>)}</View>
      <View style={[styles.across,mobile&&styles.acrossMobile]}><View style={styles.acrossHeading}><Text style={styles.eyebrow}>Intelligence</Text><Text style={styles.sectionTitle}>Across Sportabase</Text></View><View style={[styles.acrossGrid,mobile&&styles.acrossGridMobile]}>{acrossSportabase.map((item,index)=><Pressable key={item.label} onPress={()=>onOpenResult(item.resultKey)} style={({pressed})=>[styles.acrossItem,mobile&&styles.acrossItemMobile,pressed&&styles.pressed]}><Text style={[styles.acrossLabel,{color:index===0?'#818CF8':index===1?'#82E85B':'#D946EF'}]}>{item.label}</Text><Text style={styles.acrossSport}>{item.sport}</Text><Text style={styles.acrossTitle}>{item.title}</Text><Text style={styles.acrossState}>{item.state}</Text></Pressable>)}</View></View>
      <View style={[styles.future,mobile&&styles.futureMobile]}><View><Text style={styles.eyebrow}>Your Sportabase</Text><Text style={styles.futureTitle}>A place for the stories you follow.</Text></View><Text style={styles.futureNote}>Recent analyses, saved stories and watchlists stay with your Sportabase account.</Text></View>
    </Animated.View>
  </View>;
}

const styles=StyleSheet.create({
  page:{position:'relative'},hero:{paddingTop:48,maxWidth:940},heroMobile:{paddingTop:34},headline:{color:palette.text,fontSize:56,lineHeight:61,letterSpacing:-1.8,fontWeight:'800',maxWidth:780},headlineMobile:{fontSize:39,lineHeight:44,letterSpacing:-1.1,maxWidth:340},copy:{color:palette.secondary,fontSize:17,lineHeight:26,maxWidth:710,marginTop:18},copyMobile:{fontSize:16,lineHeight:24,marginTop:15,maxWidth:340},actionRow:{flexDirection:'row',alignItems:'stretch',width:'100%',maxWidth:900,marginTop:28},actionRowMobile:{flexDirection:'column',gap:12,marginTop:24},input:{flex:1,minHeight:58,borderWidth:1,borderColor:'rgba(197,206,198,.30)',backgroundColor:'rgba(11,15,13,.92)',color:palette.text,fontSize:16,paddingHorizontal:20,borderRadius:9},buttonShell:{minWidth:166,marginLeft:10,borderRadius:9,overflow:'hidden'},buttonMobile:{marginLeft:0,minWidth:0,width:'100%'},button:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:18,paddingHorizontal:26},buttonText:{color:palette.ground,fontSize:17,fontWeight:'800'},arrow:{color:palette.ground,fontSize:21},pressed:{opacity:.68},error:{color:'#FB9AA9',fontSize:14,lineHeight:20,marginTop:12},
  sectionHeader:{marginTop:72,paddingTop:25,borderTopWidth:1,borderTopColor:palette.line,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',gap:20},eyebrow:{color:palette.teal,fontSize:11,fontWeight:'900',letterSpacing:1.35,textTransform:'uppercase'},sectionTitle:{color:palette.text,fontSize:27,lineHeight:34,fontWeight:'800',letterSpacing:-.4,marginTop:5},sectionNote:{color:palette.muted,fontSize:12},sportSelector:{gap:8,paddingVertical:22,paddingRight:24},sportOption:{minHeight:34,justifyContent:'center',paddingHorizontal:12,borderBottomWidth:2,borderBottomColor:'transparent'},sportOptionActive:{borderBottomColor:palette.lime},sportText:{color:palette.muted,fontSize:14,fontWeight:'700'},sportTextActive:{color:palette.text},storyGrid:{flexDirection:'row',gap:32},storyGridMobile:{flexDirection:'column',gap:0},storyline:{flex:1,minWidth:0,borderTopWidth:1,borderTopColor:'rgba(197,206,198,.24)',paddingTop:18,paddingBottom:10},storylineMobile:{paddingVertical:20,borderBottomWidth:1,borderBottomColor:palette.line},storyTop:{flexDirection:'row',justifyContent:'space-between',gap:12},storyContext:{color:palette.muted,fontSize:11,fontWeight:'800',letterSpacing:1,textTransform:'uppercase'},storyIndex:{color:'rgba(152,164,157,.45)',fontSize:11,fontWeight:'800'},storyTitle:{color:palette.text,fontSize:21,lineHeight:27,fontWeight:'800',marginTop:14,maxWidth:360},storyDescription:{color:palette.secondary,fontSize:14,lineHeight:21,marginTop:10,maxWidth:370},storySignal:{flexDirection:'row',alignItems:'center',gap:8,marginTop:18,flexWrap:'wrap'},signalMark:{width:7,height:7,borderRadius:4},storyState:{fontSize:11,fontWeight:'900',textTransform:'uppercase',letterSpacing:.7},storyCount:{color:palette.muted,fontSize:12},
  across:{marginTop:72,paddingTop:26,borderTopWidth:1,borderTopColor:palette.line},acrossMobile:{marginTop:54},acrossHeading:{marginBottom:24},acrossGrid:{flexDirection:'row'},acrossGridMobile:{flexDirection:'column'},acrossItem:{flex:1,minWidth:0,paddingHorizontal:26,paddingBottom:8,borderLeftWidth:1,borderLeftColor:palette.line},acrossItemMobile:{paddingHorizontal:0,paddingVertical:20,borderLeftWidth:0,borderTopWidth:1,borderTopColor:palette.line},acrossLabel:{fontSize:11,fontWeight:'900',letterSpacing:1,textTransform:'uppercase'},acrossSport:{color:palette.muted,fontSize:11,fontWeight:'700',marginTop:12},acrossTitle:{color:palette.text,fontSize:18,lineHeight:24,fontWeight:'700',marginTop:7,maxWidth:350},acrossState:{color:palette.secondary,fontSize:12,marginTop:12},future:{marginTop:68,paddingVertical:28,borderTopWidth:1,borderBottomWidth:1,borderColor:palette.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:40},futureMobile:{marginTop:48,flexDirection:'column',alignItems:'flex-start',gap:14},futureTitle:{color:palette.text,fontSize:18,fontWeight:'700',marginTop:7},futureNote:{color:palette.muted,fontSize:13,lineHeight:20,maxWidth:460},
});
