import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useRef, useState } from 'react';
import { Animated, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { DesignLabHeader } from './DesignLabHeader';
import { DesktopDetails, MobileDetailSection } from './DesignLabSection';
import { evidenceTones, getMeritBand, palette } from './design-lab-theme';
import type { DetailKey, MockResult, RelatedReport } from './mock-results';

export const RESULT_REVEAL_MS = 520;
const fixtureUrl = (file: string) => `http://localhost:8082/design-lab-fixtures/${file}`;

function SourceStrip({ result, mobile }: { result: MockResult; mobile: boolean }) {
  const source = result.source;
  return <View style={[s.sourceStrip, mobile && s.sourceStripMobile]}>
    {[source.publisher, source.platform, source.sport, source.subject, source.published].map((value, index) => <View key={`${value}-${index}`} style={s.sourceItem}><Text style={[s.sourceText, index === 0 && s.sourcePrimary]}>{value}</Text></View>)}
    <Pressable accessibilityRole="link" onPress={() => Linking.openURL(fixtureUrl(result.fixtureFile))} style={s.sourceLink}><Text style={s.sourceLinkText}>{source.linkLabel} ↗</Text></Pressable>
  </View>;
}

function RelatedRow({ item, accent }: { item: RelatedReport; accent: string }) {
  return <Pressable accessibilityRole="link" onPress={() => Linking.openURL(fixtureUrl(item.fixtureFile))} style={({ pressed }) => [s.relatedRow, pressed && s.pressed]}>
    <View style={s.relatedTop}><Text style={s.relatedSource}>{item.source}</Text><Text style={s.relatedTime}>{item.time}</Text></View>
    <Text style={s.relatedHeadline}>{item.headline}</Text>
    <View style={s.relationshipRow}><View style={[s.relationshipMark, { backgroundColor: accent }]} /><Text style={[s.relationship, { color: accent }]}>{item.relationship}</Text><Text style={s.sourceType}>{item.sourceType}</Text><Text style={s.external}>↗</Text></View>
  </Pressable>;
}

function RelatedRail({ result, accent }: { result: MockResult; accent: string }) {
  return <View style={s.rail}><Text style={s.sectionLabel}>Who else is reporting this?</Text><Text style={s.railIntro}>Reports concerning the same claim, people and event window.</Text>
    <View style={s.relatedList}>{result.related.map(item => <RelatedRow key={`${item.source}-${item.headline}`} item={item} accent={accent} />)}</View>
    <View style={s.evolution}><Text style={s.sectionLabel}>Story evolution</Text><Text style={s.railIntro}>A local preview of how the reporting landscape is changing.</Text>{result.evolution.map(([label, detail], index) => <View key={label} style={s.evolutionRow}><View style={s.evolutionTrack}><View style={[s.evolutionDot, { borderColor: accent }]} />{index < result.evolution.length - 1 ? <View style={s.evolutionLine} /> : null}</View><View style={s.evolutionCopy}><Text style={s.evolutionLabel}>{label}</Text><Text style={s.evolutionDetail}>{detail}</Text></View></View>)}</View>
  </View>;
}

export function DesignLabResult({ result, mobile, onHome, onSettled, showHeader = true }: { result: MockResult; mobile: boolean; onHome: () => void; onSettled?: () => void; showHeader?: boolean }) {
  const [openMobile, setOpenMobile] = useState<DetailKey | null>(null), enter = useRef(new Animated.Value(0)).current;
  useEffect(() => { Animated.timing(enter, { toValue: 1, duration: RESULT_REVEAL_MS, useNativeDriver: false }).start(({ finished }) => finished && onSettled?.()); }, [enter, onSettled]);
  const band = getMeritBand(result.merit), tone = evidenceTones[result.tone];
  const rise = (delay: number) => ({ opacity: enter.interpolate({ inputRange: [0, delay, Math.min(1, delay + .34)], outputRange: [0, 0, 1] }), transform: [{ translateY: enter.interpolate({ inputRange: [0, delay, Math.min(1, delay + .34)], outputRange: [8, 8, 0] }) }] });
  const primary = <Animated.View style={[s.primary, mobile && s.primaryMobile, rise(.18)]}><View style={[s.merit, mobile && s.full]}><Text style={s.label}>Merit</Text><Text style={[s.score, mobile && s.scoreMobile]}>{result.merit}</Text><LinearGradient colors={[...band.colors]} start={{ x: 0, y: .5 }} end={{ x: 1, y: .5 }} style={s.meritRail} /><Text style={[s.band, { color: band.colors[1] }]}>{band.key}</Text><Text style={s.disclaimer}>Informational value, not truth probability.</Text></View><View style={[s.intelligence, mobile && s.full]}><Text style={[s.label, { color: tone.accent }]}>Evidence status</Text><View style={s.statusRow}><View style={[s.statusMark, { borderColor: tone.accent }]} /><Text style={[s.status, mobile && s.statusMobile]}>{result.evidenceStatus}</Text></View><View style={s.metrics}>{[['Corroboration', result.corroboration], ['Independence', result.independence], ['Sources located', String(result.sources)], ['Verification pairs', String(result.verificationPairs)], ['Merit impact', result.meritImpact]].map(([label, value]) => <View key={label} style={s.metricRow}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>)}</View></View></Animated.View>;
  const summary = <Animated.View style={[s.summary, rise(.35)]}><Text style={s.sectionLabel}>Summary</Text><View style={[s.summaryGrid, mobile && s.summaryMobile]}>{result.summary.map((item, index) => <Animated.View key={item} style={[s.summaryItem, mobile && s.summaryItemMobile, { opacity: enter.interpolate({ inputRange: [0, .41 + index * .04, .64 + index * .04], outputRange: [0, 0, 1] }) }]}><Text style={[s.summaryNumber, { color: tone.accent }]}>0{index + 1}</Text><Text style={s.summaryText}>{item}</Text></Animated.View>)}</View></Animated.View>;
  const details = <Animated.View style={rise(.56)}>{mobile ? <View style={s.mobileDetails}><Text style={s.sectionLabel}>Analysis details</Text>{(['merit', 'evidence'] as DetailKey[]).map(key => <MobileDetailSection key={key} detail={result.details[key]} open={openMobile === key} accent={tone.accent} onPress={() => setOpenMobile(openMobile === key ? null : key)} />)}</View> : <DesktopDetails result={result} accent={tone.accent} />}</Animated.View>;
  return <View style={[s.page, mobile && { maxWidth: '100%', overflow: 'hidden' }]}>{showHeader?<Animated.View style={rise(0)}><DesignLabHeader mobile={mobile} onHome={onHome} onAnother={onHome} showAnother /></Animated.View>:null}<Animated.View style={[s.intro, mobile && s.introMobile, mobile && { width: '100%', maxWidth: '100%' }, rise(.05)]}><Text style={[s.type, { color: tone.accent }]}>{result.contentType}</Text><Text style={[s.claim, mobile && s.claimMobile, mobile && { width: '100%', maxWidth: '100%', flexShrink: 1 }]}>{result.claim}</Text><SourceStrip result={result} mobile={mobile} /></Animated.View>{mobile ? <>{primary}{summary}<Animated.View style={rise(.5)}><RelatedRail result={result} accent={tone.accent} /></Animated.View>{details}</> : <View style={s.dossier}><View style={s.mainColumn}>{primary}{summary}{details}</View><Animated.View style={[s.sideColumn, rise(.45)]}><RelatedRail result={result} accent={tone.accent} /></Animated.View></View>}</View>;
}

const s = StyleSheet.create({
  page:{position:'relative'},intro:{maxWidth:1030,paddingTop:38},introMobile:{paddingTop:26},type:{fontSize:13,lineHeight:18,fontWeight:'800',letterSpacing:1.1,textTransform:'uppercase'},claim:{color:palette.text,fontSize:43,lineHeight:51,letterSpacing:-1.3,fontWeight:'800',marginTop:12,maxWidth:1000},claimMobile:{fontSize:30,lineHeight:36,letterSpacing:-.7,marginTop:9},sourceStrip:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',marginTop:22,borderTopWidth:1,borderBottomWidth:1,borderColor:palette.line,minHeight:46},sourceStripMobile:{marginTop:18,paddingVertical:8},sourceItem:{paddingRight:13,marginRight:13,borderRightWidth:1,borderRightColor:palette.line},sourceText:{color:palette.muted,fontSize:12,lineHeight:20},sourcePrimary:{color:palette.secondary,fontWeight:'800'},sourceLink:{minHeight:36,justifyContent:'center',paddingHorizontal:6},sourceLinkText:{color:palette.teal,fontSize:12,fontWeight:'800'},
  dossier:{flexDirection:'row',alignItems:'flex-start',gap:48,width:'100%'},mainColumn:{width:'68%',minWidth:0,flexShrink:1},sideColumn:{width:'32%',minWidth:0,paddingTop:42,flexShrink:1},primary:{flexDirection:'row',gap:40,width:'100%',marginTop:42,alignItems:'flex-start'},primaryMobile:{flexDirection:'column',gap:30,marginTop:28,paddingTop:24,borderTopWidth:1,borderTopColor:palette.line},merit:{width:'34%',flexGrow:0,flexShrink:0,paddingLeft:2},full:{width:'100%'},label:{color:palette.muted,textTransform:'uppercase',letterSpacing:1.1,fontSize:12,fontWeight:'800'},score:{color:palette.text,fontSize:100,lineHeight:106,fontWeight:'900',letterSpacing:-5,marginTop:6,fontVariant:['tabular-nums']},scoreMobile:{fontSize:80,lineHeight:88,letterSpacing:-3.5},meritRail:{height:3,width:170,marginTop:4},band:{fontSize:12,fontWeight:'900',letterSpacing:1,textTransform:'uppercase',marginTop:10},disclaimer:{color:palette.muted,fontSize:13,lineHeight:19,marginTop:12,maxWidth:230},intelligence:{flex:1,minWidth:0},statusRow:{flexDirection:'row',alignItems:'center',gap:12,marginTop:11,marginBottom:17},statusMark:{width:16,height:16,borderRadius:9,borderWidth:3},status:{color:palette.text,fontSize:25,lineHeight:31,fontWeight:'800'},statusMobile:{fontSize:24,lineHeight:30},metrics:{borderTopWidth:1,borderTopColor:palette.line},metricRow:{minHeight:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:14,borderBottomWidth:1,borderBottomColor:palette.line},metricLabel:{color:palette.secondary,fontSize:13,flex:1},metricValue:{color:palette.text,fontSize:13,fontWeight:'700',textAlign:'right',maxWidth:'56%'},
  summary:{borderTopWidth:1,borderTopColor:palette.line,marginTop:44,paddingTop:27},sectionLabel:{color:palette.muted,textTransform:'uppercase',letterSpacing:1.05,fontSize:11,fontWeight:'900',marginBottom:17},summaryGrid:{flexDirection:'row',flexWrap:'wrap',columnGap:30,rowGap:22},summaryMobile:{flexDirection:'column',gap:0},summaryItem:{width:'47%',flexDirection:'row',gap:13,paddingTop:12,borderTopWidth:1,borderTopColor:'rgba(197,206,198,.16)'},summaryItemMobile:{width:'100%',paddingVertical:15},summaryNumber:{fontSize:11,fontWeight:'900',letterSpacing:.5,paddingTop:3},summaryText:{color:palette.secondary,fontSize:15,lineHeight:23,flex:1},
  rail:{borderLeftWidth:1,borderLeftColor:palette.line,paddingLeft:28},railIntro:{color:palette.muted,fontSize:12,lineHeight:18,marginTop:-8,marginBottom:8},relatedList:{marginTop:4},relatedRow:{paddingVertical:17,borderTopWidth:1,borderTopColor:palette.line},pressed:{opacity:.62},relatedTop:{flexDirection:'row',justifyContent:'space-between',gap:10},relatedSource:{color:palette.text,fontSize:13,fontWeight:'800',flex:1},relatedTime:{color:palette.muted,fontSize:11},relatedHeadline:{color:palette.secondary,fontSize:14,lineHeight:20,fontWeight:'600',marginTop:7},relationshipRow:{flexDirection:'row',alignItems:'center',gap:7,marginTop:10,flexWrap:'wrap'},relationshipMark:{width:5,height:5,borderRadius:3},relationship:{fontSize:10,fontWeight:'900',textTransform:'uppercase',letterSpacing:.45},sourceType:{color:palette.muted,fontSize:10},external:{color:palette.muted,fontSize:12,marginLeft:'auto'},evolution:{marginTop:36,paddingTop:24,borderTopWidth:1,borderTopColor:palette.line},evolutionRow:{flexDirection:'row',gap:11,minHeight:53},evolutionTrack:{width:12,alignItems:'center'},evolutionDot:{width:8,height:8,borderRadius:4,borderWidth:2,backgroundColor:palette.ground},evolutionLine:{width:1,flex:1,backgroundColor:palette.line},evolutionCopy:{flex:1,paddingBottom:14},evolutionLabel:{color:palette.secondary,fontSize:11,fontWeight:'800',textTransform:'uppercase',letterSpacing:.5},evolutionDetail:{color:palette.muted,fontSize:12,lineHeight:18,marginTop:3},mobileDetails:{marginTop:42,borderBottomWidth:1,borderBottomColor:palette.line},
});
