import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'expo-router';
import { Animated, Easing, Platform, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ANALYZING_LOOP_MS, DesignLabAnalyzing } from './DesignLabAnalyzing';
import { DesignLabGeometry, type BackgroundIdentity } from './DesignLabGeometry';
import { DesignLabHome } from './DesignLabHome';
import { DesignLabResult } from './DesignLabResult';
import { palette } from './design-lab-theme';
import { useDesignLabFonts, WordmarkContext, type WordmarkCandidate } from './design-lab-fonts';
import { fixtureByPath, mockResults, type MockResult, type ResultKey } from './mock-results';
type LabState = 'home' | ResultKey; type Phase = 'home' | 'homeExit' | 'analyzing' | 'resolving' | 'result';
type Times = { pressed?: number; analyzing?: number; complete?: number; resultStart?: number; settled?: number };
const controls: { key: LabState; label: string }[] = [{ key: 'home', label: 'Home' }, ...Object.values(mockResults).map(r => ({ key: r.key, label: r.evidenceStatus }))];
const delayOptions: [string, number | null][] = [['AUTO', null], ['1.2s', 1200], ['2.5s', 2500], ['5s', 5000], ['10s', 10000]];
const wordmarkOptions: { key: WordmarkCandidate; label: string }[] = [{ key: 'uppercase-a', label: 'A PERFORMANCE' }, { key: 'uppercase-b', label: 'B BALANCED' }, { key: 'uppercase-c', label: 'C MINIMAL' }, { key: 'oxanium', label: 'REF OXANIUM' }];
const now = () => typeof performance !== 'undefined' ? performance.now() : Date.now(); const seconds = (value?: number) => value === undefined ? '—' : `${(value / 1000).toFixed(2)}s`;

export function SportabaseDesignLab({ initialState = 'home', previewWidth, initialMotionDebug = false, initialBackground = 'sb', initialWordmark = 'uppercase-b' }: { initialState?: LabState; previewWidth?: number; initialMotionDebug?: boolean; initialBackground?: BackgroundIdentity; initialWordmark?: WordmarkCandidate }) {
  const [fontsLoaded, fontError] = useDesignLabFonts();
  const router = useRouter();
  const { width } = useWindowDimensions(), layoutWidth = previewWidth ?? width, mobile = layoutWidth < 700;
  const pageGutter = layoutWidth >= 1200 ? 68 : layoutWidth >= 700 ? 40 : 20;
  const shellWidth = Math.max(Math.min(layoutWidth - pageGutter * 2, 1304), 280);
  const [state, setState] = useState<LabState>(initialState), [phase, setPhase] = useState<Phase>(initialState === 'home' ? 'home' : 'result');
  const [result, setResult] = useState<MockResult | null>(initialState === 'home' ? null : mockResults[initialState]), [url, setUrl] = useState(''), [error, setError] = useState('');
  const [override, setOverride] = useState<number | null>(null), [times, setTimes] = useState<Times>({}), [labOpen, setLabOpen] = useState(false), [motionDebug, setMotionDebug] = useState(initialMotionDebug), [background, setBackground] = useState<BackgroundIdentity>(initialBackground), [wordmark, setWordmark] = useState<WordmarkCandidate>(initialWordmark);
  const homeExit = useRef(new Animated.Value(0)).current;
  const goHome = useCallback(() => { setState('home'); setPhase('home'); setResult(null); setError(''); setTimes({}); homeExit.setValue(0); router.setParams({ state: 'home' }); }, [homeExit, router]);
  const direct = (key: LabState) => { if (key === 'home') return goHome(); const next = mockResults[key]; setState(key); setResult(next); setUrl(`/design-lab-fixtures/${next.fixtureFile}`); setPhase('result'); setTimes({ resultStart: now() }); router.setParams({ state: key }); };
  const analyze = (submitted: string) => {
    let name = ''; try { name = new URL(submitted, 'http://localhost:8082').pathname.split('/').pop() ?? ''; } catch { name = submitted.split('/').pop() ?? ''; }
    const match = fixtureByPath[name]; if (!match) { setError('Use one of the six local fixture URLs for this prototype.'); return; }
    const pressed = now(), wait = override ?? match.delayMs; setError(''); setUrl(submitted); setResult(match); setState(match.key); setTimes({ pressed }); setPhase('homeExit'); router.setParams({ state: match.key });
    Animated.timing(homeExit, { toValue: 1, duration: 430, easing: Easing.out(Easing.cubic), useNativeDriver: Platform.OS !== 'web' }).start(() => {
      const entered = now(); setTimes(current => ({ ...current, analyzing: entered })); setPhase('analyzing');
      setTimeout(() => { setTimes(current => ({ ...current, complete: now() })); setPhase('resolving'); }, wait);
    });
  };
  const revealResult = useCallback(() => { setTimes(current => ({ ...current, resultStart: now() })); setPhase('result'); if (result) router.setParams({ state: result.key }); }, [result, router]);
  useEffect(() => { if (initialState === state || phase === 'homeExit' || phase === 'analyzing' || phase === 'resolving') return; homeExit.setValue(0); setState(initialState); setError(''); if (initialState === 'home') { setResult(null); setPhase('home'); } else { const next = mockResults[initialState]; setResult(next); setUrl(`/design-lab-fixtures/${next.fixtureFile}`); setPhase('result'); } }, [homeExit, initialState, phase, state]);
  useEffect(() => { setBackground(initialBackground); }, [initialBackground]);
  useEffect(() => { setWordmark(initialWordmark); }, [initialWordmark]);
  const changeBackground = (next: BackgroundIdentity) => { setBackground(next); router.setParams({ bg: next }); };
  const changeWordmark = (next: WordmarkCandidate) => { setWordmark(next); router.setParams({ wordmark: next }); };
  const settled = useCallback(() => { const stamp = now(); setTimes(current => { const next = { ...current, settled: stamp }; if (result && next.pressed) console.info('[Sportabase Design Lab timing]', { fixture: result.fixtureLabel, waitMs: override ?? result.delayMs, homeToAnalyzingMs: (next.analyzing ?? 0) - next.pressed, analyzingMs: (next.complete ?? 0) - (next.analyzing ?? 0), analyzingToResultMs: (next.resultStart ?? 0) - (next.complete ?? 0), resultRevealMs: stamp - (next.resultStart ?? 0), totalMs: stamp - next.pressed }); return next; }); }, [override, result]);
  if (!fontsLoaded && !fontError) return <SafeAreaView style={styles.safe} />;
  if (fontError) return <SafeAreaView style={styles.safe}><View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 }}><Text style={{ color: palette.text, fontSize: 18, fontWeight: '700' }}>Design Lab fonts could not load.</Text><Text style={{ color: palette.muted, fontSize: 14, marginTop: 8 }}>Reload the local prototype to try again.</Text></View></SafeAreaView>;
  let content;
  if (phase === 'home' || phase === 'homeExit') content = <DesignLabHome mobile={mobile} onAnalyze={analyze} onOpenResult={direct} error={error} initialUrl={url} exitProgress={homeExit} />;
  else if (phase === 'analyzing' || phase === 'resolving') content = <DesignLabAnalyzing mobile={mobile} url={url} exiting={phase === 'resolving'} onExitComplete={revealResult} motionDebug={motionDebug} />;
  else if (result) {
    content = <DesignLabResult key={result.key} result={result} mobile={mobile} onHome={goHome} onSettled={settled} />;
  } else content = null;
  const wait = override ?? result?.delayMs;
  const watermark = phase === 'home' || phase === 'homeExit' ? <DesignLabGeometry mode="home" identity={background} compact={mobile} transition={homeExit} motionDebug={motionDebug} /> : phase === 'result' && result ? <DesignLabGeometry mode="result" identity={background} compact={mobile} variant={result.key} motionDebug={motionDebug} /> : null;
  return <SafeAreaView style={styles.safe}>{watermark}<ScrollView style={styles.scroll} contentContainerStyle={[styles.scrollContent, labOpen && styles.scrollContentLabOpen, labOpen && { paddingBottom: 210 }, mobile && styles.scrollContentMobile]} keyboardShouldPersistTaps="handled"><View style={[styles.shell, mobile && styles.shellMobile, mobile ? { width: shellWidth, paddingHorizontal: 0, alignSelf: 'flex-start', marginLeft: pageGutter, marginRight: 0 } : { width: shellWidth, paddingHorizontal: 0, alignSelf: 'center', marginLeft: 'auto', marginRight: 'auto' }]}><WordmarkContext.Provider value={wordmark}>{content}</WordmarkContext.Provider></View></ScrollView>
    {labOpen ? <Pressable accessibilityRole="button" accessibilityState={{ selected: motionDebug }} onPress={() => setMotionDebug(value => !value)} style={{ position: 'absolute', right: mobile ? 16 : 24, bottom: 166, minHeight: 32, justifyContent: 'center', paddingHorizontal: 10, borderRadius: 6, backgroundColor: motionDebug ? 'rgba(32,201,176,.18)' : 'rgba(16,21,18,.98)', borderWidth: 1, borderColor: motionDebug ? palette.teal : palette.line }}><Text style={{ color: motionDebug ? palette.text : palette.muted, fontSize: 10, fontWeight: '900', letterSpacing: .7 }}>MOTION DEBUG {motionDebug ? 'ON' : 'OFF'}</Text></Pressable> : null}
    {labOpen ? <View style={[styles.lab, mobile && styles.labMobile]}><Pressable accessibilityRole="button" accessibilityLabel="Collapse Design Lab controls" onPress={() => setLabOpen(false)} style={styles.labTop}><Text style={styles.labTitle}>DESIGN LAB</Text><Text style={styles.collapse}>×</Text></Pressable><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.controls}>{controls.map(control => <Pressable key={control.key} onPress={() => direct(control.key)} style={[styles.control, state === control.key && styles.controlActive]}><Text style={[styles.controlText, state === control.key && styles.controlTextActive]}>{control.label}</Text></Pressable>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.readout}><Text style={styles.readoutText}>Fixture: {result?.fixtureLabel ?? '—'}</Text><Text style={styles.readoutText}>Wait: {seconds(wait)}</Text><Text style={styles.readoutText}>Home → Analyze: {times.pressed && times.analyzing ? seconds(times.analyzing - times.pressed) : '—'}</Text><Text style={styles.readoutText}>Analyzing: {times.analyzing && times.complete ? seconds(times.complete - times.analyzing) : '—'}</Text><Text style={styles.readoutText}>Result transition: {times.complete && times.resultStart ? seconds(times.resultStart - times.complete) : '—'}</Text><Text style={styles.readoutText}>Result reveal: {times.resultStart && times.settled ? seconds(times.settled - times.resultStart) : '—'}</Text><Text style={styles.readoutText}>Loop: {seconds(ANALYZING_LOOP_MS)}</Text>{delayOptions.map(([label, value]) => <Pressable key={label} onPress={() => setOverride(value)} style={[styles.delay, override === value && styles.delayActive]}><Text style={styles.delayText}>{label}</Text></Pressable>)}</ScrollView></View> : <Pressable accessibilityRole="button" accessibilityLabel="Open Design Lab controls" onPress={() => setLabOpen(true)} style={styles.labTab}><Text style={styles.labTabText}>DESIGN LAB</Text></Pressable>}
    {labOpen ? <View style={{ position: 'absolute', left: mobile ? 8 : 24, bottom: 138, minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 8, borderRadius: 6, backgroundColor: 'rgba(16,21,18,.98)', borderWidth: 1, borderColor: palette.line }}><Text style={styles.readoutText}>BACKGROUND</Text>{(['sb', 'wordmark'] as const).map(option => <Pressable key={option} onPress={() => changeBackground(option)} style={[styles.delay, background === option && styles.delayActive]}><Text style={[styles.delayText, background === option && { color: palette.text }]}>{option === 'sb' ? 'FULL SB' : 'SPORTABASE'}</Text></Pressable>)}</View> : null}
    {labOpen ? <View style={{ position: 'absolute', left: mobile ? 8 : 24, bottom: 204, minHeight: 32, maxWidth: mobile ? Math.max(280, layoutWidth - 16) : undefined, flexDirection: 'row', flexWrap: mobile ? 'wrap' : 'nowrap', alignItems: 'center', gap: 6, paddingHorizontal: 8, borderRadius: 6, backgroundColor: 'rgba(16,21,18,.98)', borderWidth: 1, borderColor: palette.line }}><Text style={styles.readoutText}>WORDMARK</Text>{wordmarkOptions.map(option => <Pressable key={option.key} accessibilityState={{ selected: wordmark === option.key }} onPress={() => changeWordmark(option.key)} style={[styles.delay, wordmark === option.key && styles.delayActive]}><Text style={[styles.delayText, wordmark === option.key && { color: palette.text }]}>{option.label}</Text></Pressable>)}</View> : null}
  </SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: palette.ground }, scroll: { flex: 1 }, scrollContent: { minHeight: '100%', paddingBottom: 72 }, scrollContentLabOpen: { paddingBottom: 178 }, scrollContentMobile: { paddingBottom: 86 }, shell: { maxWidth: 1256, alignSelf: 'stretch', width: 'auto', marginHorizontal: 'auto', paddingHorizontal: 28, paddingBottom: 54 }, shellMobile: { alignSelf: 'flex-start', marginLeft: 20, marginRight: 0, paddingHorizontal: 0, paddingBottom: 30 }, labTab: { position: 'absolute', right: 14, bottom: 12, minHeight: 34, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 7, backgroundColor: 'rgba(16,21,18,.97)', borderWidth: 1, borderColor: 'rgba(181,243,107,.28)' }, labTabText: { color: palette.lime, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, lab: { position: 'absolute', left: 16, right: 16, bottom: 14, minHeight: 118, backgroundColor: 'rgba(16,21,18,.98)', borderWidth: 1, borderColor: 'rgba(181,243,107,.24)', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, gap: 5 }, labMobile: { left: 8, right: 8, bottom: Platform.OS === 'web' ? 8 : 4 }, labTop: { minHeight: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, labTitle: { color: palette.lime, fontSize: 10, fontWeight: '900', letterSpacing: 1.1 }, collapse: { color: palette.secondary, fontSize: 18 }, controls: { alignItems: 'center', gap: 5 }, control: { minHeight: 30, justifyContent: 'center', paddingHorizontal: 9, borderRadius: 6, borderWidth: 1, borderColor: 'transparent' }, controlActive: { backgroundColor: 'rgba(32,201,176,.12)', borderColor: palette.teal }, controlText: { color: palette.muted, fontSize: 11, fontWeight: '700' }, controlTextActive: { color: palette.text }, readout: { alignItems: 'center', gap: 14, paddingRight: 8 }, readoutText: { color: palette.muted, fontSize: 10, fontWeight: '600' }, delay: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 5, borderWidth: 1, borderColor: palette.line }, delayActive: { borderColor: palette.lime }, delayText: { color: palette.secondary, fontSize: 9, fontWeight: '800' } });
